name: artiver
description: articles time saver

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  auto_route: ^4.2.1
  connectivity_plus: ^1.0.4
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_localizations:
    sdk: flutter
  fpdart: ^0.0.9
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+1
  intl: ^0.17.0
  mockito: ^5.3.0

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  injectable_generator: ^1.5.3
  test: ^1.22.0

flutter:
  uses-material-design: true
  generate: true

